services:
  db:
    image: postgres:17
    container_name: wb_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  postgres_data: